After payment, need to delete the shopping cart in session and cookies (#568)
* After payment, need to delete the shopping cart in session and cookies

* Fix error CS1574: XML comment has cref attribute 'ShoppingCartPersistenceBase' that could not be resolved

* Update src/Libraries/OrchardCore.Commerce.Abstractions/Abstractions/IShoppingCartPersistence.cs

Co-authored-by: Sára El-Saig <sara.el-saig@lombiq.com>

* Update test/OrchardCore.Commerce.Tests/Fakes/FakeCartStorage.cs

Co-authored-by: Sára El-Saig <sara.el-saig@lombiq.com>

* After Review

* Update src/Modules/OrchardCore.Commerce/Services/ShoppingCartPersistenceBase.cs

* Update src/Libraries/OrchardCore.Commerce.Abstractions/Abstractions/IShoppingCartPersistence.cs

---------

Co-authored-by: Sára El-Saig <sara.el-saig@lombiq.com>